---
title: "Single Cell Analysis(E-MTAB-8107 dataset)"
author: ""
format: html
editor: visual
---

E-MTAB-8107 is a CRC single cell dataset which is created by Qian (first author)

```{r}
#| label: E-MTAB-8107 scRNA-seq preprocessing
#| label: For this part, we got some references from the Koncina (first author) article. The wibsite of the article is https://www.nature.com/articles/s41467-023-39953-w

#setwd('F:\\NC_code\\Single_cell_analysis\\E-MTAB-8107_DataSet')

metadata = fread('2099-Colorectalcancer_metadata.csv',
                 data.table = F,
                 header = T) %>% column_to_rownames(var = 'Cell')

counts = Read10X(data.dir = '.\\CRC_10x',#matrix.mtx, genes.tsv (or features.tsv), and barcodes.tsv patg
                 unique.features = T,
                 strip.suffix = F)
dge = CreateSeuratObject(counts = counts, 
                          meta.data = metadata,
                          project   = "E-MTAB-8107",
                          min.cells  = 10,     # only genes > 10 cells
                          min.features  = 200,
                          names.field = 1,
                          names.delim  = "_")    # only cells with > 200 genes)
dge
```

```{r}
#| label: Mitochondria genes
dge[["percent.mt"]] = PercentageFeatureSet(dge, pattern = "^MT-")
VlnPlot(dge,features = c('nFeature_RNA','nCount_RNA','percent.mt'),ncol = 3,pt.size = F)
```

```{r}
#| label: Filter genes 
dge = subset(dge, subset =  nFeature_RNA <= 6000 & percent.mt <= 15)
VlnPlot(dge,features = c('nFeature_RNA','nCount_RNA','percent.mt'),ncol = 3,pt.size = F)
```

```{r}
#| label: Normalise by log transfromation
dge = NormalizeData(object = dge,
                  normalization.method = "LogNormalize",
                  scale.factor = 10000)
#| label: Find high variable genes
x_low_cutoff  = 0.0125
x_high_cutoff = 3 
y_cutoff      = 0.5 
y_high_cutoff = Inf
dge = FindVariableFeatures(object = dge,
                            mean.function = ExpMean,                                 dispersion.function = LogVMR,
            mean.cutoff = c(x_low_cutoff, x_high_cutoff),
           dispersion.cutoff = c(y_cutoff, y_high_cutoff))
VariableFeaturePlot(dge)
```

```{r}
#| label: Calculate G2/M and S phase score
data("cc.genes.updated.2019")
# ssegregate this list into markers of G2/M phase and markers of S phase
dge = CellCycleScoring(object = dge,
         s.features = cc.genes.updated.2019$s.genes,
         g2m.features = cc.genes.updated.2019$g2m.genes,
        set.ident = TRUE)
#| label: scale the data while using mt, S and G2/M score as covariates to eliminate confounding factors
dge = ScaleData(dge,
                vars.to.regress = c("nCount_RNA",
                                     "percent.mt",
                                     "S.Score",
                                     "G2M.Score"))
#| label: Reduce dimensions by PCA program, 40 npcs was chosen for analysis
dge = RunPCA(object= dge, 
              npcs = 40, 
              ndims.print = 1:5,     
              nfeatures.print = 5,     
              use.imputed = FALSE,
              rev.pca = FALSE)
DimHeatmap(dge,dims = 1:5,cells = 400,balanced = T)
ElbowPlot(dge,ndims = 50)
```

```{r}
#| label: Reduce dimensions to 2 levels using UMAP
dge = RunUMAP(dge,
               reduction.use = "pca",
               dims = 1:40,
               seed.use = 42)
#| label: Show distribution of all cell type refer to original reference
DimPlot(object = dge, 
        pt.size = .1, 
        group.by = "CellType", 
        cols="Paired")
```

```{r}
#| label: Re-calculate K-NN and re-cluster for our own analysis
dge = FindNeighbors(dge, reduction = "pca", dims = 1:40 ) %>% FindClusters()
DimPlot(object = dge, 
        pt.size = .1)
```

Seurat's function 'FindAllMarkers' was used to identify Markers for each clusters and define distinct subpopulations.

```{r}
#| label: 'FindAllMarkers' to identify cluster-specific gene markers
setwd('F:\\NC_code\\Single_cell_analysis\\E-MTAB-8107_DataSet')
getwd()
dge = readRDS('E-MTAB-8107_seurat_dge.rds')
Idents(dge) = dge@meta.data$RNA_snn_res.0.8
DimPlot(dge)
DefaultAssay(dge) = 'RNA'
dge = NormalizeData(dge)
all_genes = rownames(dge)
dge = ScaleData(dge,features = all_genes)
dge_diff_markers = FindAllMarkers(object = dge,
                                  logfc.threshold = 0.1,
                                  min.pct = 0.1,
                                  only.pos = T,
                                  test.use = 'wilcox')
```

```{r}
#| label: save 'FindAllMarkers' results
write.csv(dge_diff_markers,'dge_diff_markers.csv')
```

Subset top100 marker genes of each cluster and identify the subpopulations combined with canonical markers.

```{r}
#| label: Combine canonical markers with top100 marker genes to identify each cluster.
dge_diff_markers_top_100 = dge_diff_markers %>% group_by(cluster) %>% 
  top_n(n=100,wt = avg_log2FC)
Epthelial_genes = c('EPCAM','SOX9','CD24','CD133','CDH1','KRT8','KRT19','KRT20')
Endothelial_genes = c('PECAM1','CDH5','VIM','VWF','LCN2','ENG','CD34','CD31','GNGL1','CLDN5')
Fibroblast_genes = c('VIM','THY1','COL1A1','COL1A2','COL11A1','COL3A1','DCN','ACTA2','CXCL14','CALD1','IGFBP7','FAP','COL6A1')
Enteric_glial_genes = c('S100B','CDH2','NRXN1','PLP1','GPM6B','SOX10',
                        'CLU','CRYAB')
B_genes = c('CD79A','CD79B','PTPRC','MS4A1','CD19','JCHAIN','DERL3',
            'MZB1','CD20','CD38','BANK1')
T_genes = c('CD3D','CD3E','CD3G','CD8A','TRBC2','TRAC','CD247','CD96',
            'CD4')
Mast_genes = c('KIT','TPSAB1','IL1RL1','MS4A2','TPSB2','CPA3')
Myeloid_genes = c('CD14','CD68','C1QB','LYZ','FCGR3A','CD163','FCG2R',
                  'MPEG1','SAMHD1','S100A9','S100A12')
gene_sets <- list(
  Epthelial = Epthelial_genes,
  Endothelial = Endothelial_genes,
  Fibroblast = Fibroblast_genes,
  Enteric_glial = Enteric_glial_genes,
  B_cells = B_genes,
  T_cells = T_genes,
  Mast = Mast_genes,
  Myeloid = Myeloid_genes
)

results_list <- lapply(names(gene_sets), function(gene_set_name) {
  dge_diff_markers_top_100 %>%
    group_by(cluster) %>%
    summarise(
      !!gene_set_name := paste(intersect(gene, gene_sets[[gene_set_name]]), collapse = ", "),
      .groups = 'drop'
    )
})

final_result <- reduce(results_list, left_join, by = "cluster")
```

```{r}
#| label: Output the results 
write.csv(final_result,'UniqueSubpopulations_FindAllMarkers_combined_canonical markers.csv',row.names = F)
```

```{r}
#| label: Reannotate the clusters 
Idents(dge) = dge@meta.data$RNA_snn_res.0.8
pdf('dge_Dimplot_res_0.8.pdf',width = 7,height = 5)
DimPlot(dge)
dev.off()
Anno = read_csv('UniqueSubpopulations_FindAllMarkers_combined_canonical markers.csv') %>% dplyr::select(c('cluster','celltype_FindAllMarkers')) %>% pull(celltype_FindAllMarkers)
dge_findallmarkers = RenameIdents(dge,
                          '0' = 'T cells',
                          '1' = 'Myeloid cells',
                          '2' = 'Epithelial cells',
                          '3' = 'B cells',
                          '4' = 'B cells',
                          '5' = 'Endothelial cells',
                          '6' = 'T cells',
                          '7' = 'Fibroblasts',
                          '8' = 'Fibroblasts',
                          '9' = 'Epithelial cells',
                          '10' = 'T cells',
                          '11' = 'Fibroblasts',
                          '12' = 'Fibroblasts',
                          '13' = 'Epithelial cells',
                          '14' = 'Epithelial cells',
                          '15' = 'Epithelial cells',
                          '16' = 'T cells',
                          '17' = 'Myeloid cells',
                          '18' = 'B cells',
                          '19' = 'B cells',
                          '20' = 'Enteric glial cells',
                          '21' = 'Mast cells',
                          '22' = 'Fibroblasts',
                          '23' = 'B cells',
                          '24' = 'Fibroblasts',
                          '25' = 'Epithelial cells',
                          '26' = 'Fibroblasts',
                          '27' = 'Unknown',
                          '28' = 'Fibroblasts',
                          '29' = 'Endothelial cells',
                          '30' = 'Unknown')
DimPlot(dge_findallmarkers)
dge_findallmarkers_cells = DimPlot(dge_findallmarkers)$data
write.csv(dge_findallmarkers_cells,'dge_findallmarkers_cells.csv',row.names = T)
```

```{r}
#| label: Combine the findallmarker celltypes with the celltypes of original article.
metadata = read_csv('2099-Colorectalcancer_metadata.csv')
dge_findallmarkers_cells$Cell = rownames(dge_findallmarkers_cells)
colnames(dge_findallmarkers_cells) [3] = 'CellType_FindAllMarkers'
final_metadata = left_join(metadata,dge_findallmarkers_cells,by = 'Cell')
final_metadata = na.omit(final_metadata)
final_metadata %>% tabyl(CellType,CellType_FindAllMarkers)
final_metadata = final_metadata %>% 
  mutate(final_celltype = case_when(
  CellType == 'Cancer' & CellType_FindAllMarkers == 'Epithelial cells' ~ 'Epithelial cells',
 CellType == 'Cancer' & CellType_FindAllMarkers == 'Unknown' ~ 'Epithelial cells',
 CellType == 'Myeloid' & CellType_FindAllMarkers == 'Myeloid cells' ~ 'Myeloid cells',
 CellType == 'T_cell' & CellType_FindAllMarkers == 'T cells' ~ 
   'T cells',
 CellType == 'Fibroblast' & CellType_FindAllMarkers == 'Fibroblasts' ~ 'Fibroblasts',
 CellType == 'B_cell' & CellType_FindAllMarkers == 'B cells' ~ 'B cells',
 CellType == 'EC' & CellType_FindAllMarkers == 'Endothelial cells' ~ 'Endothelial cells',
 CellType == 'Enteric_glia' & CellType_FindAllMarkers == 'Enteric glial cells' ~ 'Enteric glial cells',
 CellType == 'Mast_cell' & CellType_FindAllMarkers == 'Mast cells' ~ 'Mast cells' ))
final_metadata_filtered = na.omit(final_metadata)
```

```{r}
#| label: Save the final RDS document of E-MTAB-8107 dataset. 
cells_to_keep = rownames(dge@meta.data) %in% final_metadata_filtered$Cell
dge_final = subset(dge, cells = rownames(dge@meta.data)[cells_to_keep])
identical(rownames(dge_final@meta.data),final_metadata_filtered$Cell)
dge_final@meta.data$Final_Celltype = final_metadata_filtered$final_celltype
DimPlot(dge_final,group.by = 'Final_Celltype')
saveRDS(dge_final,'dge_final_E-MTAB-8107_seurat_dge.rds')
Idents(dge_final) = dge_final@meta.data$Final_Celltype
write.csv(DimPlot(dge_final)$data,'dge_final_cells.csv',row.names = T)
```

Figure 6A

```{r}
#| label: Set path
setwd('F:\\NC_code\\Single_cell_analysis\\E-MTAB-8107_DataSet')
dge = readRDS('dge_final_E-MTAB-8107_seurat_dge.rds')
out.path = getwd()
```

```{r}
#| label: write_pdf function
write_pdf <- function (x, 
                       filename, 
                       width = NA, 
                       height = NA, 
                       units = "cm", ...) {
  temp <- tempfile() 
  on.exit(unlink(temp)) 
  grDevices::cairo_pdf(temp, family = "sans", ...) 
  if (isTRUE(is.na(width)) && !"null" %in% unitType(x$widths)) 
    width <- convertWidth(sum(x$widths), unitTo = units, 
                          valueOnly = TRUE)
  if (isTRUE(is.na(height)) && !"null" %in% unitType(x$heights)) 
    height <- convertHeight(sum(x$heights), unitTo = units, 
                            valueOnly = TRUE)
  
  width <- grid::convertWidth(unit(width, units = units), unitTo = "inches", valueOnly = TRUE)
  height <- grid::convertHeight(unit(height, units = units), unitTo = "inches", valueOnly = TRUE)
  invisible(dev.off())
  grDevices::cairo_pdf(filename, family = "sans", width = width, height = height, ...)  
  grid::grid.draw(x) 
  invisible(dev.off()) 
  filename
}
```

```{r}
#| label: Figure6A
Figure6A = DimPlot(dge,pt.size =  0.1)+
  scale_colour_manual(values = rev(brewer.pal(n = 9, name = "Spectral")))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank())
Figure6A
```

```{r}
#| label: Figure6A output
set_panel_size(p = Figure6A,
               width = unit(5,'cm'),
               height = unit(5,'cm')) %>% 
  write_pdf(file.path(out.path,'Figure6A_output.pdf'))
```

Figure6B

```{r}
#| label: Figure6B data prepare
genes_list = tribble(~features.plot,~celltype,
                   'CD14','(Myeloid cells)',
                   'CD68','(Myeloid cells)',
                   'CD3E','(T cells)',
                   'CD3D','(T cells)',
                   'COL1A1','(Fibroblasts)',
                   'COL1A2','(Fibroblasts)',
                   'PECAM1','(Endothelial cells)',
                   'VWF','(Endothelial cells)',
                   'CPA3','(Mast cells)',
                   'KIT','(Mast cells)',
                   'EPCAM','(Epithelial cells)',
                   'KRT8','(Epithelial cells)',
                   'CD79A','(B cells)',
                   'CD79B','(B cells)',
                   'PLP1','(Enteric glial cells)',
                   'S100B','(Enteric glial cells)') %>% 
  mutate(celltype = fct_inorder(celltype)) %>% 
  tidyr::unite(label,
               features.plot,
               celltype,
               sep = " ",
               remove = F)
```

```{r}
#| label: Dot_Figure6B function
Dot_Figure6B = function(data){
  data %>% mutate(avg.exp.log2 = log2(avg.exp+1)) %>% 
    ggplot(aes(x = id,y = features.plot))+
    geom_point(mapping = aes_string(size = 'pct.exp', fill = 'avg.exp.log2'),  
               shape = 21,  
               color = "black", 
               stroke = 1)+
    scale_size(range = c(0.3,6))+
    cowplot::theme_cowplot()+
    theme_bw()+
    theme(axis.title = element_blank(),
          panel.grid = element_blank(),
          axis.text.x = element_text(angle = 45,hjust = 1))+
    scale_fill_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))+
    guides(size = guide_legend(title = 'Percent Expressed'))
} 
```

```{r}
#| label: Figure6B
Figure6B = DotPlot(dge,
            features = genes_list %>%  pull(features.plot),
            assay = 'RNA',
            scale = F,
            cluster.idents = T
)$data %>% 
  mutate(id = fct_relevel(id,'Myeloid cells','T cells','Fibroblasts','Endothelial cells','Mast cells','Epithelial cells','B cells','Enteric glial cells')) %>%
  left_join(genes_list) %>% 
  mutate(features.plot = fct_reorder(features.plot,as.numeric(celltype))) %>% 
  Dot_Figure6B()
Figure6B
```

```{r}
#| label: Figure6B output
set_panel_size(p = Figure6B,
               width = unit(10.5,'cm'),
               height = unit(10.5,'cm')) %>% 
  write_pdf(file.path(out.path,'Figure6B_output.pdf'))
```

Figure6C

```{r}
#| label: Figure6C 
Figure6C = lapply(c('NCL', 'CD44', 'EPCAM', 'CXCR4', 'TFRC', 'MUC1', 'PROM1', 'CEACAM5', 'SELP'), function(gene) {
  p = FeaturePlot(dge, features = gene, pt.size = 0.1, order = TRUE) +
    scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu"))) +
    theme_bw() +
    theme(panel.grid = element_blank(),
          axis.title.x = element_blank(),  
          axis.title.y = element_blank())
  
  if (gene != 'NCL' && gene != 'TFRC' ) {
    p <- p + theme(panel.border = element_blank(),
                   axis.text.x = element_blank(),
                   axis.text.y = element_blank(),
                   axis.ticks.x = element_blank(),
                   axis.ticks.y = element_blank())  
  }
  
  return(p)
})
combined_plot = ggpubr::ggarrange(plotlist = Figure6C, ncol = 4, nrow = 3, common.legend = TRUE, legend = "bottom")
```

```{r}
#| label: Show Featureplot of 9 genes
combined_plot
```

```{r}
#| label: Figure6C output
set_panel_size(p = combined_plot,
               width = unit(66.7,'cm'),
               height = unit(50,'cm')) %>% 
  write_pdf(file.path(out.path,'Figure6C_output.pdf'))
```
