---
title: "FindAllMarkers"
author: "Chen Xin"
format: html
editor: visual
---

Seurat's function 'FindAllMarkers' was used to identify Markers for each clusters and define distinct subpopulations.

```{r}
#| label: 'FindAllMarkers' to identify cluster-specific gene markers
setwd('F:\\NC_code\\Single_cell_analysis\\E-MTAB-8107_DataSet')
getwd()
dge = readRDS('E-MTAB-8107_seurat_dge.rds')
Idents(dge) = dge@meta.data$RNA_snn_res.0.8
DimPlot(dge)
DefaultAssay(dge) = 'RNA'
dge = NormalizeData(dge)
all_genes = rownames(dge)
dge = ScaleData(dge,features = all_genes)
dge_diff_markers = FindAllMarkers(object = dge,
                                  logfc.threshold = 0.1,
                                  min.pct = 0.1,
                                  only.pos = T,
                                  test.use = 'wilcox')
```

```{r}
#| label: save 'FindAllMarkers' results
write.csv(dge_diff_markers,'dge_diff_markers.csv')
```

Subset top100 marker genes of each cluster and identify the subpopulations combined with canonical markers.

```{r}
#| label: Combine canonical markers with top100 marker genes to identify each cluster.
dge_diff_markers_top_100 = dge_diff_markers %>% group_by(cluster) %>% 
  top_n(n=100,wt = avg_log2FC)
Epthelial_genes = c('EPCAM','SOX9','CD24','CD133','CDH1','KRT8','KRT19','KRT20')
Endothelial_genes = c('PECAM1','CDH5','VIM','VWF','LCN2','ENG','CD34','CD31','GNGL1','CLDN5')
Fibroblast_genes = c('VIM','THY1','COL1A1','COL1A2','COL11A1','COL3A1','DCN','ACTA2','CXCL14','CALD1','IGFBP7','FAP','COL6A1')
Enteric_glial_genes = c('S100B','CDH2','NRXN1','PLP1','GPM6B','SOX10',
                        'CLU','CRYAB')
B_genes = c('CD79A','CD79B','PTPRC','MS4A1','CD19','JCHAIN','DERL3',
            'MZB1','CD20','CD38','BANK1')
T_genes = c('CD3D','CD3E','CD3G','CD8A','TRBC2','TRAC','CD247','CD96',
            'CD4')
Mast_genes = c('KIT','TPSAB1','IL1RL1','MS4A2','TPSB2','CPA3')
Myeloid_genes = c('CD14','CD68','C1QB','LYZ','FCGR3A','CD163','FCG2R',
                  'MPEG1','SAMHD1','S100A9','S100A12')
gene_sets <- list(
  Epthelial = Epthelial_genes,
  Endothelial = Endothelial_genes,
  Fibroblast = Fibroblast_genes,
  Enteric_glial = Enteric_glial_genes,
  B_cells = B_genes,
  T_cells = T_genes,
  Mast = Mast_genes,
  Myeloid = Myeloid_genes
)

results_list <- lapply(names(gene_sets), function(gene_set_name) {
  dge_diff_markers_top_100 %>%
    group_by(cluster) %>%
    summarise(
      !!gene_set_name := paste(intersect(gene, gene_sets[[gene_set_name]]), collapse = ", "),
      .groups = 'drop'
    )
})

final_result <- reduce(results_list, left_join, by = "cluster")
```

```{r}
#| label: Output the results 
write.csv(final_result,'UniqueSubpopulations_FindAllMarkers_combined_canonical markers.csv',row.names = F)
```

```{r}
#| label: Reannotate the clusters 
Idents(dge) = dge@meta.data$RNA_snn_res.0.8
pdf('dge_Dimplot_res_0.8.pdf',width = 7,height = 5)
DimPlot(dge)
dev.off()
Anno = read_csv('UniqueSubpopulations_FindAllMarkers_combined_canonical markers.csv') %>% dplyr::select(c('cluster','celltype_FindAllMarkers')) %>% pull(celltype_FindAllMarkers)
dge_findallmarkers = RenameIdents(dge,
                          '0' = 'T cells',
                          '1' = 'Myeloid cells',
                          '2' = 'Epithelial cells',
                          '3' = 'B cells',
                          '4' = 'B cells',
                          '5' = 'Endothelial cells',
                          '6' = 'T cells',
                          '7' = 'Fibroblasts',
                          '8' = 'Fibroblasts',
                          '9' = 'Unknown',
                          '10' = 'T cells',
                          '11' = 'Fibroblasts',
                          '12' = 'Fibroblasts',
                          '13' = 'Epithelial cells',
                          '14' = 'Epithelial cells',
                          '15' = 'Unknown',
                          '16' = 'T cells',
                          '17' = 'Myeloid cells',
                          '18' = 'B cells',
                          '19' = 'B cells',
                          '20' = 'Enteric glial cells',
                          '21' = 'Mast cells',
                          '22' = 'Fibroblasts',
                          '23' = 'B cells',
                          '24' = 'Fibroblasts',
                          '25' = 'Epithelial cells',
                          '26' = 'Fibroblasts',
                          '27' = 'Unknown',
                          '28' = 'Fibroblasts',
                          '29' = 'Endothelial cells',
                          '30' = 'Unknown')
DimPlot(dge_findallmarkers)
dge_findallmarkers_cells = DimPlot(dge_findallmarkers)$data
write.csv(dge_findallmarkers_cells,'dge_findallmarkers_cells.csv',row.names = T)
```

```{r}
#| label: Combine the findallmarker celltypes with the celltypes of original article.
metadata = read_csv('2099-Colorectalcancer_metadata.csv')
dge_findallmarkers_cells$Cell = rownames(dge_findallmarkers_cells)
colnames(dge_findallmarkers_cells) [3] = 'CellType_FindAllMarkers'
final_metadata = left_join(metadata,dge_findallmarkers_cells,by = 'Cell')
final_metadata = na.omit(final_metadata)
final_metadata %>% tabyl(CellType,CellType_FindAllMarkers)
final_metadata = final_metadata %>% 
  mutate(final_celltype = case_when(
  CellType == 'Cancer' & CellType_FindAllMarkers == 'Epithelial cells' ~ 'Epithelial cells',
 CellType == 'Cancer' & CellType_FindAllMarkers == 'Unknown' ~ 'Epithelial cells',
 CellType == 'Myeloid' & CellType_FindAllMarkers == 'Myeloid cells' ~ 'Myeloid cells',
 CellType == 'T_cell' & CellType_FindAllMarkers == 'T cells' ~ 
   'T cells',
 CellType == 'Fibroblast' & CellType_FindAllMarkers == 'Fibroblasts' ~ 'Fibroblasts',
 CellType == 'B_cell' & CellType_FindAllMarkers == 'B cells' ~ 'B cells',
 CellType == 'EC' & CellType_FindAllMarkers == 'Endothelial cells' ~ 'Endothelial cells',
 CellType == 'Enteric_glia' & CellType_FindAllMarkers == 'Enteric glial cells' ~ 'Enteric glial cells',
 CellType == 'Mast_cell' & CellType_FindAllMarkers == 'Mast cells' ~ 'Mast cells' ))
final_metadata_filtered = na.omit(final_metadata)
```

```{r}
#| label: Save the final RDS document of E-MTAB-8107 dataset. 
cells_to_keep = rownames(dge@meta.data) %in% final_metadata_filtered$Cell
dge_final = subset(dge, cells = rownames(dge@meta.data)[cells_to_keep])
identical(rownames(dge_final@meta.data),final_metadata_filtered$Cell)
dge_final@meta.data$Final_Celltype = final_metadata_filtered$final_celltype
DimPlot(dge_final,group.by = 'Final_Celltype')
saveRDS(dge_final,'dge_final_E-MTAB-8107_seurat_dge.rds')
Idents(dge_final) = dge_final@meta.data$Final_Celltype
write.csv(DimPlot(dge_final)$data,'dge_final_cells.csv',row.names = T)
```
